version: '3.3'

services:

  bot:
    container_name: bot
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - DISCORD_GUILD=${DISCORD_GUILD}
      - DISCORD_TOKEN=${DISCORD_TOKEN}